In [1]:
import numpy as np

In [2]:
revenue=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [3]:
print(revenue*75)

[[15000 16500 18750]
 [ 5100  5925  7875]
 [ 8250 10500 13500]
 [ 6000  6375  6750]]


In [7]:
unitssold=np.array([[50,60,25],[10,13,5],[40,70,52]])
priceperunit=np.array([[20],[30],[15]])
print(np.dot(unitssold.T,priceperunit))

[[1900]
 [2640]
 [1430]]
